appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: gw3occ9lbTRO8HdG+NvKHNBZhh235/dRpemKQVoL44X2SiXz24mpyna8HupCgw1+QmTSmytRzjyKjIvvvWRv+WrAfIGw+twFpefBrIB4Yb1yu7DAqZHinWz1hEZQsnsxsFHT0fkcOjQoTwzw6A7gE446jV3L1ShBAQKBuSmYLpCDSMdJdq5sbmdCzZsmFxmBnR4z/Z3f2E/O7OiPpSnMqL9yb3l4+OMTNvcxi7fl9ZA56XuyDTiWrr3e/JFRlwcy1akypALyONBewpC4ePqtqd/jlN8yT02mlpiN4lc3G+c7Q0yriu9VHq2A3xyhGQ5MeWp1U34+8IgGwzdz5E8NeoNi9WrvjLw4ZDeoEhQ84W64JexXz2OWRXrgJbt+dUYolU3LIklO/NWhAx7+Gdl5M/mEjdS1ksBTUygbZbj2H4Cfsrqus38/CxkS2DPJ6e7Ay+dp21oOoEctgD0j0UyXbKnObprzJ8ngNZps23Lj8GY4tZR0kOKkja47az/ZtdTxVne5JDzgjsLzPhSrh1gqZ2JbphkBhWF/E43rrbyHu+9ov+HiKH3TVcjT6pcFy8DsmRbBYFbvr6ZpVTFUmXMarF6d+s2gkwJ0kiSgS99dWg3jouVlgHPI+rhBBOKgEEHoKItOnP3ehIXMjeXx9zuwv7JPB7JY8m+MMIOB4x3PD8I=}
bot:
  automerge: true
